### ISSUE TITLE
login page is not fully responsive

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/qurandl#15]
background color of #wrapper does not cover full width of screen. we can fix it by applying the color to body.

**Comment by imranertaza** [comment]
Hi,
Is anybody working on this issue? I am interested to work on this issue. Please inform me if anybody is not working on this issue or if it is not already solved.
Thank you

**Comment by edrisranjbar** [comment]
Hi @imranertaza , thanks for informing us. Go a head, it is still open and not solved.

**Comment by edrisranjbar** [comment]
Hi @imranertaza, should I start working on this issue? keep me posted about your progress! Thanks man 👍🏻

**Comment by imranertaza** [comment]
Hi @edrisranjbar 
Yes, I will give you give you update about this issue.

**Comment by imranertaza** [comment]
Hi @edrisranjbar 
Please assign me for this issue. 
Thank you

**Comment by imranertaza** [comment]
Hi
I have fixed this issue and please check the pull request.
Thank you

**Comment by edrisranjbar** [comment]
@imranertaza your PR has been reviewed. Thanks for your contribution.

**Comment by edrisranjbar** [comment]
your `PR` has been merged to the develop branch. did you check for responsiveness for mobile? I see you used a `CSS` width property, wasn't it better to just use Bootstrap classes for responsive so that we are sure it works in all media query breakpoints?
@imranertaza

**Comment by imranertaza** [comment]
Hi
Yes, I have checked it and It is working for all query breakpoints. I had tried to use Bootstrap, but I did not find any code that sets a card with fixed width. 

I searched on Google and saw bootstrap documents, most of them used inline style to set the width. But as you know, inline style is not suitable for SEO and also we should avoid inline style as much as possible to make the code clean. That's why I used it in our custom CSS file.
Thank you

**Comment by edrisranjbar** [comment]
Thanks a lot dear @imranertaza ❤️  for your contribution.

**Comment by imranertaza** [comment]
Thank you too. I wish to contribute more after the EID Day. 
Happy EID Day brother!

**Comment by edrisranjbar** [comment]
Happy Eid bro, I wish you all the bests.

> Thank you too. I wish to contribute more after the EID Day. Happy EID Day brother!
